# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17f825f778f5b391115a3cef4e41a3e949e57faf020f26db51d9b60192cd79094cb4bb91458dd165c56b790ad839b5979691b9a7eec5db474ec1779ec72cf732

test:
  secret_key_base: c0d6720e0ca97d5f0ee5606ba389038bb9d18c89066040e0227d5eb450ab865a4503a4e92d354da943c69ba92760cac64f2fb102a571297a50775c371feb7f79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
